main:
  push:
    - name: sync-to-github
      imports: https://cnb.cool/InspireWorks/tokens/-/blob/main/github.yml
      stages:
        - name: sync
          jobs:
            - name: sync-to-github
              image: docker.cnb.cool/cnb/plugins/git-sync:latest
              settings:
                target_url: https://github.com/XiaoYangTech/ListextEditor.git
                target_token: ${GITHUB_TOKEN}
                sync_branches: main master
                sync_tags: true

master:
  push:
    - name: sync-to-github
      imports: https://cnb.cool/InspireWorks/tokens/-/blob/main/github.yml
      stages:
        - name: sync
          jobs:
            - name: sync-to-github
              image: docker.cnb.cool/cnb/plugins/git-sync:latest
              settings:
                target_url: https://github.com/XiaoYangTech/ListextEditor.git
                target_token: ${GITHUB_TOKEN}
                sync_branches: main master
                sync_tags: true